-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 20:03:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`provincia` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`canton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`canton` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ProvinciaId` INT(10) UNSIGNED NOT NULL,
  `Nombre` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Area` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `Poblacion` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `canton_` (`ProvinciaId` ASC),
  CONSTRAINT `canton_`
    FOREIGN KEY (`ProvinciaId`)
    REFERENCES `proyecto`.`provincia` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 707
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`distrito` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CantonId` INT(10) UNSIGNED NOT NULL,
  `Nombre` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `distrito_CantonId` (`CantonId` ASC),
  CONSTRAINT `distrito_CantonId`
    FOREIGN KEY (`CantonId`)
    REFERENCES `proyecto`.`canton` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 70606
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`especie` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`familia` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Enabled` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`genero` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`familiaXgenero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`familiaXgenero` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdGenero` INT(10) UNSIGNED NOT NULL,
  `IdFamilia` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_familiaXgenero_genero1_idx` (`IdGenero` ASC),
  INDEX `fk_familiaXgenero_familia1_idx` (`IdFamilia` ASC),
  CONSTRAINT `fk_familiaXgenero_genero1`
    FOREIGN KEY (`IdGenero`)
    REFERENCES `proyecto`.`genero` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_familiaXgenero_familia1`
    FOREIGN KEY (`IdFamilia`)
    REFERENCES `proyecto`.`familia` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`colector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`colector` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Enabled` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`validador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`validador` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Enabled` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`especieXgenero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`especieXgenero` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdEspecie` INT UNSIGNED NOT NULL,
  `IdFamiliaXgenero` INT UNSIGNED NOT NULL,
  `Autoria` VARCHAR(100) NOT NULL DEFAULT '',
  `Sinonimias` VARCHAR(100) NOT NULL,
  INDEX `fk_especieXgenero_especie1_idx` (`IdEspecie` ASC),
  PRIMARY KEY (`Id`),
  INDEX `fk_especieXgenero_familiaXgenero1_idx` (`IdFamiliaXgenero` ASC),
  CONSTRAINT `fk_especieXgenero_especie1`
    FOREIGN KEY (`IdEspecie`)
    REFERENCES `proyecto`.`especie` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_especieXgenero_familiaXgenero1`
    FOREIGN KEY (`IdFamiliaXgenero`)
    REFERENCES `proyecto`.`familiaXgenero` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`muestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`muestra` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdDistrito` INT(10) UNSIGNED NOT NULL,
  `IdColector` INT NOT NULL,
  `IdValidador` INT NOT NULL,
  `IdEspecieXgenero` INT NOT NULL,
  `Localidad` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Latitud` VARCHAR(50) NOT NULL,
  `Longitud` VARCHAR(50) NOT NULL,
  `Altitud` VARCHAR(50) NOT NULL,
  `FechaIngreso` TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
  `FechaColecto` TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
  `nota` VARCHAR(500) NOT NULL DEFAULT '',
  PRIMARY KEY (`Id`),
  INDEX `fk_muestra_distrito1_idx` (`IdDistrito` ASC),
  INDEX `fk_muestra_colector1_idx` (`IdColector` ASC),
  INDEX `fk_muestra_validador1_idx` (`IdValidador` ASC),
  INDEX `fk_muestra_especieXgenero1_idx` (`IdEspecieXgenero` ASC),
  CONSTRAINT `fk_muestra_distrito1`
    FOREIGN KEY (`IdDistrito`)
    REFERENCES `proyecto`.`distrito` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_muestra_colector1`
    FOREIGN KEY (`IdColector`)
    REFERENCES `proyecto`.`colector` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_muestra_validador1`
    FOREIGN KEY (`IdValidador`)
    REFERENCES `proyecto`.`validador` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_muestra_especieXgenero1`
    FOREIGN KEY (`IdEspecieXgenero`)
    REFERENCES `proyecto`.`especieXgenero` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`ficha_historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`ficha_historial` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ProvinciaId` INT(11) NOT NULL,
  `CantonId` INT(11) NOT NULL,
  `DistritoId` INT(11) NOT NULL,
  `Localidad` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Latitud` INT(11) NOT NULL,
  `Longitud` INT(11) NOT NULL,
  `Altitud` INT(11) NOT NULL,
  `DeterminadorId` INT(11) NOT NULL,
  `FechaIngreso` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FechaColecto` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`usuario` (
  `Id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Clave` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Nombre` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `Rol` VARCHAR(126) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`fertilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`fertilidad` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Enabled` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`fertilidadXmuestra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`fertilidadXmuestra` (
  `IdMuestra` INT(10) UNSIGNED NOT NULL,
  `IdFertilidad` INT NOT NULL,
  INDEX `fk_fertilidadXmuestra_muestra1_idx` (`IdMuestra` ASC),
  INDEX `fk_fertilidadXmuestra_Fertilidad1_idx` (`IdFertilidad` ASC),
  CONSTRAINT `fk_fertilidadXmuestra_muestra1`
    FOREIGN KEY (`IdMuestra`)
    REFERENCES `proyecto`.`muestra` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fertilidadXmuestra_Fertilidad1`
    FOREIGN KEY (`IdFertilidad`)
    REFERENCES `proyecto`.`fertilidad` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Imagen` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdMuestra` INT(10) UNSIGNED NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Url` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Imagen_muestra1_idx` (`IdMuestra` ASC),
  CONSTRAINT `fk_Imagen_muestra1`
    FOREIGN KEY (`IdMuestra`)
    REFERENCES `proyecto`.`muestra` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
